"""create all tables

Revision ID: 5b0f0abafd4f
Revises: 
Create Date: 2026-04-20 19:39:41.747309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0f0abafd4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('biografia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autores_id'), 'autores', ['id'], unique=False)
    op.create_index(op.f('ix_autores_nome'), 'autores', ['nome'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('editoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('ano_publicacao', sa.Integer(), nullable=True),
    sa.Column('quantidade_total', sa.Integer(), nullable=False),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('editora_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['editora_id'], ['editoras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index(op.f('ix_livros_id'), 'livros', ['id'], unique=False)
    op.create_table('livro_autor',
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.PrimaryKeyConstraint('livro_id', 'autor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livro_autor')
    op.drop_index(op.f('ix_livros_id'), table_name='livros')
    op.drop_table('livros')
    op.drop_table('editoras')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_autores_nome'), table_name='autores')
    op.drop_index(op.f('ix_autores_id'), table_name='autores')
    op.drop_table('autores')
    # ### end Alembic commands ###
