name: Notify Frontend

on:
  push:
    paths: ['frontend/**']
  pull_request:
    paths: ['frontend/**']

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_FRONTEND_WEBHOOK }}
        with:
          args: '🚀 **Frontend** foi alterado\nBranch: ${{ github.ref_name }}\nAutor: ${{ github.actor }}'
