name: Notify Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reviewed, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_PR_WEBHOOK }}
        with:
          args: '📋 Pull Request ${{ github.event.action }}\nTítulo: ${{ github.event.pull_request.title }}\nAutor: ${{ github.event.pull_request.user.login }}'
