name: Notify Backend

on:
  push:
    paths: ['backend/**']
  pull_request:
    paths: ['backend/**']

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_BACKEND_WEBHOOK }}
        with:
          args: '🔧 **Backend** foi alterado\nBranch: ${{ github.ref_name }}\nAutor: ${{ github.actor }}'
